### ISSUE TITLE
While Using Horizon capture it crash in android oreo 8.0 and 8.1 device

### ISSUE THREAD

**Issue by jankice** [HorizonCamera/HorizonSDK-Android#1] opened 2018-07-04 05:34 UTC
Crash report as below:
Using latest horizon sdk
```
java.lang.RuntimeException: 
 
 at android.hardware.Camera.native_takePicture (Native Method)
 
  at android.hardware.Camera.takePicture (Camera.java:1448)
 
  at com.hvt.horizonSDK.CameraEncoder.a (SourceFile:378)
 
  at com.hvt.horizonSDK.CameraEncoder.a (SourceFile:58)
 
  at com.hvt.horizonSDK.CameraEncoder$a.handleMessage (SourceFile:1243)
 
  at android.os.Handler.dispatchMessage (Handler.java:105)
 
  at android.os.Looper.loop (Looper.java:164)
 
  at com.hvt.horizonSDK.CameraEncoder.run (SourceFile:791)
 
  at java.lang.Thread.run (Thread.java:764)
```

**Comment by Petrakeas** [comment] 2018-07-04 09:56
@jankice I am not able to reproduce it on my Android 8.0 and 8.1 devices.
Can you reproduce this crash using in the "Simple Camera" app in the repo? 

Is there any camera related information on the logcat regarding the specific RuntimeException?

**Comment by Petrakeas** [comment] 2018-12-06 10:28
I am closing this issue as Horizon SDK works correctly on Android 8.0 and 8.1 devices.

**Closed as completed by Petrakeas** 2018-12-06 10:28 UTC
